// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOkOheVmwaDi4Ut54JgsxvA8gcHcCLUxQ',
    appId: '1:572537004224:web:f9e8bb79bfe67f8e99cd25',
    messagingSenderId: '572537004224',
    projectId: 'study-time-2e716',
    authDomain: 'study-time-2e716.firebaseapp.com',
    storageBucket: 'study-time-2e716.firebasestorage.app',
    measurementId: 'G-9H4F4KXN5R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtZErx5N-CWsneNCB06eOiHKQhltUCexg',
    appId: '1:572537004224:android:242fea83a847905c99cd25',
    messagingSenderId: '572537004224',
    projectId: 'study-time-2e716',
    storageBucket: 'study-time-2e716.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5rRXY8x-wNu48ADGs_Gko6lDlxk8LaCo',
    appId: '1:572537004224:ios:167a2b7ddf60d76399cd25',
    messagingSenderId: '572537004224',
    projectId: 'study-time-2e716',
    storageBucket: 'study-time-2e716.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5rRXY8x-wNu48ADGs_Gko6lDlxk8LaCo',
    appId: '1:572537004224:ios:167a2b7ddf60d76399cd25',
    messagingSenderId: '572537004224',
    projectId: 'study-time-2e716',
    storageBucket: 'study-time-2e716.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOkOheVmwaDi4Ut54JgsxvA8gcHcCLUxQ',
    appId: '1:572537004224:web:dbfa29b967c6cb1c99cd25',
    messagingSenderId: '572537004224',
    projectId: 'study-time-2e716',
    authDomain: 'study-time-2e716.firebaseapp.com',
    storageBucket: 'study-time-2e716.firebasestorage.app',
    measurementId: 'G-TF54531TNP',
  );
}
